//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AICPDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class jobseekerprofile
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> highestdegree { get; set; }
        public Nullable<int> Experience { get; set; }
        public int categoryid { get; set; }
        public Nullable<int> subcategoryid { get; set; }
        public string CurrentCompanyName { get; set; }
        public Nullable<int> CurrentSalary { get; set; }
        public string ResumeName { get; set; }
        public System.DateTime createddate { get; set; }
        public System.DateTime modifieddate { get; set; }
    
        public virtual user user { get; set; }
    }
}
