//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AICPDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class userdetail
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public int RoleID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Zipcode { get; set; }
        public string WorkContact { get; set; }
        public string MobileContact { get; set; }
        public string EmailID { get; set; }
        public System.DateTime createddate { get; set; }
        public System.DateTime modifieddate { get; set; }
        public Nullable<int> categoryid { get; set; }
        public Nullable<int> subcategoryid { get; set; }
       public string companyname { get; set; }
    
        public virtual category category { get; set; }
        public virtual role role { get; set; }
        public virtual subcategory subcategory { get; set; }
        public virtual user user { get; set; }
    }
}
