//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AICPDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public DateTime modifiedddate;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.jobseekerprofiles = new HashSet<jobseekerprofile>();
            this.userdetails = new HashSet<userdetail>();
            this.users_applied_job = new HashSet<users_applied_job>();
        }
    
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public int questionid { get; set; }
        public string hintanswer { get; set; }
        public System.DateTime createddate { get; set; }
        public System.DateTime modifieddate { get; set; }
        public Nullable<bool> IsForgotPassword { get; set; }
        public int hintquestion2id { get; set; }
        public string hintanswer2 { get; set; }
        public int hintquestion3id { get; set; }
        public string hintanswer3 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<jobseekerprofile> jobseekerprofiles { get; set; }
        public virtual securityquestion securityquestion { get; set; }
        public virtual securityquestion securityquestion1 { get; set; }
        public virtual securityquestion securityquestion2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userdetail> userdetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<users_applied_job> users_applied_job { get; set; }
    }
}
