//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AICPDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class users_applied_job
    {
        public int userjobapplyid { get; set; }
        public int jobid { get; set; }
        public int userid { get; set; }
        public Nullable<System.DateTime> ApplyDate { get; set; }
    
        public virtual user user { get; set; }
    }
}
